DROP TABLE IF EXISTS books;

CREATE TABLE books (
   id   BIGSERIAL PRIMARY KEY,
   title VARCHAR(255) NOT NULL,
   author VARCHAR(255) NOT NULL,
   category VARCHAR(255) NOT NULL,
   image_name VARCHAR(255)
);